// <auto-generated />
using System;
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230305174646_update_englishTranslated_wrod_table")]
    partial class updateenglishTranslatedwrodtable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.EnglishTranslatedWordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnglishWordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRightTranslated")
                        .HasColumnType("bit");

                    b.Property<Guid>("TranslatedWordId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EnglishWordId");

                    b.HasIndex("TranslatedWordId");

                    b.ToTable("EnglishTranslatedWords");
                });

            modelBuilder.Entity("DAL.Entities.EnglishWordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EnglishWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EnglishWords");
                });

            modelBuilder.Entity("DAL.Entities.TranslatedWordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TranslateWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TranslatedWords");
                });

            modelBuilder.Entity("DAL.Entities.EnglishTranslatedWordEntity", b =>
                {
                    b.HasOne("DAL.Entities.EnglishWordEntity", "EnglishWord")
                        .WithMany()
                        .HasForeignKey("EnglishWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.TranslatedWordEntity", "TranslatedWord")
                        .WithMany()
                        .HasForeignKey("TranslatedWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnglishWord");

                    b.Navigation("TranslatedWord");
                });
#pragma warning restore 612, 618
        }
    }
}
